name: Create Release ZIP

on:
  release:
    types: [published]

jobs:
  attach-zip:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Create ZIP
        run: |
          zip -r "aldes-${{ github.event.release.tag_name }}.zip" custom_components/

      - name: Upload ZIP to release
        run: |
          gh release upload "${{ github.event.release.tag_name }}" "aldes-${{ github.event.release.tag_name }}.zip"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
